export const ENV_LOAD = 'ENV_LOAD';

export const PRODUCTS_CLEAN = 'PRODUCTS_CLEAN';
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL';
export const PRODUCTS_GET_LIST_SUCCESS = 'PRODUCTS_GET_LIST_SUCCESS';
export const PRODUCTS_GET_SUCCESS = 'PRODUCTS_GET_SUCCESS';
export const PRODUCTS_RESET_ERROR = 'PRODUCTS_RESET_ERROR';
export const PRODUCTS_RESET_SELECTED = 'PRODUCTS_RESET_SELECTED';
export const PRODUCTS_START = 'PRODUCTS_START';